Replicas: 1
ExpectedClusterSize: 1
RevisionHistoryLimit: 3

Image:
  repository: localhost
  name: fragment-node
  tag: v1
  pullPolicy: Never

name: fragment-node
namespace: default

service:
  type: ClusterIP
  port: 3001

# Set toggle for volume mounting
isDev: true

# Supply our local development paths
volume:
  name: host-volume
  path: /opt/microfrontends/fragment-node/dist
  mountPath: /usr/src/app/dist
