Replicas: 1
ExpectedClusterSize: 1
RevisionHistoryLimit: 3

Image:
  repository: localhost
  name: fragment-node
  tag: v1
  pullPolicy: Always

name: fragment-node
namespace: default

service:
  type: ClusterIP
  port: 3001
