apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ .Values.name }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
        - path: /fragments/node
          backend:
            serviceName: {{ .Values.name }}
            servicePort: {{ .Values.service.port }}
