apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
spec:
  selector:
    name: {{ .Values.name }}
    namespace: {{ .Values.namespace }}
  ports:
  - port: {{ .Values.service.port }}
    targetPort: http
    protocol: TCP
    name: http
  type: {{ .Values.service.type }}
